---

- name: Check for existing Nessus Agent installation.
  stat:
    path: /Library/NessusAgent/run/sbin/nessuscli
  register: nessus_installed

- debug:
    var: nessus_installed
    verbosity: 1

# Skip all the download, copy, and install stuff if the files already exist.
- block:

  - set_fact:
      data_file_name: "NessusAgent-{{ nessus_version }}.dmg"

  - import_tasks: data_download_id.yml

  # Someday add the checksum to this.
  # Remote machines may not have Internet access. Assume Ansible box does.
  - name: Download DMG package to local tmp.
    get_url:
      url: "https://tenable-downloads-production.s3.amazonaws.com/uploads/download/file/{{ nessus_download_id.stdout }}/{{ data_file_name }}"
      dest: "{{ nessus_linux_tmp }}/{{ data_file_name }}"
      force: no
    become: no
    ignore_errors: "{{ ansible_check_mode }}"

  - name: Check if dmg is mounted already.
    stat:
      path: "/Volumes/Nessus Agent Install"
    register: nessus_agent_install_mounted

  - name: Mount dmg image for {{ app_name }}
    command: "hdiutil attach {{ nessus_linux_tmp }}/{{ data_file_name }}"
    when: not nessus_agent_install_mounted.stat.exists
    ignore_errors: "{{ ansible_check_mode }}"

  - name: Install pkg from dmg mount.
    shell: "installer -package /Volumes/Nessus\ Agent\ Install/Install\ Nessus\ Agent.pkg -target /"
    args:
      chdir: "/Volumes/Nessus Agent Install"
      creates: /Library/NessusAgent/run/sbin/nessuscli
    become: yes
    ignore_errors: "{{ ansible_check_mode }}"

  - name: Unmount dmg image.
    command: "hdiutil detach '/Volumes/Nessus Agent Install'"
    ignore_errors: "{{ ansible_check_mode }}"

  - name: Remove dmg file.
    file:
      path: "{{ nessus_linux_tmp }}/{{ data_file_name }}"
      state: absent

  when: not nessus_installed.stat.exists
