---

- set_fact:
    data_file_name: NessusAgent-{{ nessus_version }}-es{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm

- debug:
    var: data_file_name
    verbosity: 1

- import_tasks: data_download_id.yml

# Someday add the checksum to this.
# Remote machines may not have Internet access. Assume Ansible box does.
- name: Download RPM package to local tmp.
  local_action:
    module: get_url
    url: "https://tenable-downloads-production.s3.amazonaws.com/uploads/download/file/{{ nessus_download_id.stdout }}/{{ data_file_name }}"
    dest: "{{ nessus_linux_tmp }}/{{ data_file_name }}"
    force: no
  become: no
  ignore_errors: "{{ ansible_check_mode }}"

# Copy would support a URL, but doing get_url without force works like a cache.
- name: Upload RPM to remote.
  copy:
    src: "{{ nessus_linux_tmp }}/{{ data_file_name }}"
    dest: "{{ nessus_linux_tmp }}/{{ data_file_name }}"
    force: no
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install RPM package.
  yum:
    name: "{{ nessus_linux_tmp }}/{{ data_file_name }}"
    state: present
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
