---

- set_fact:
    nessus_ubuntu_architecture: "{{ (ansible_architecture == 'x86_64') | ternary('amd64','i386') }}"

- set_fact:
    data_file_name: NessusAgent-{{ nessus_version }}-ubuntu1110_{{ nessus_ubuntu_architecture }}.deb

- import_tasks: data_download_id.yml

# Someday add the checksum to this.
# Remote machines may not have Internet access. Assume Ansible box does.
- name: Download DEB package to local tmp.
  local_action:
    module: get_url
    url: "https://tenable-downloads-production.s3.amazonaws.com/uploads/download/file/{{ nessus_download_id.stdout }}/{{ data_file_name }}"
    dest: "{{ nessus_linux_tmp }}/{{ data_file_name }}"
    force: no
  become: no
  ignore_errors: "{{ ansible_check_mode }}"

# Copy would support a URL, but doing get_url without force works like a cache.
- name: Upload DEB to remote.
  copy:
    src: "{{ nessus_linux_tmp }}/{{ data_file_name }}"
    dest: "{{ nessus_linux_tmp }}/{{ data_file_name }}"
    force: no
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install DEB package.
  apt:
    deb: "{{ nessus_linux_tmp }}/{{ data_file_name }}"
    state: present
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
